name: tcge-cfmedip-seq-pipeline-r
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconductor-medips
  - bioconductor-bsgenome.hsapiens.ucsc.hg19
  - bioconductor-bsgenome.hsapiens.ucsc.hg38
  - bioconductor-bsgenome.scerevisiae.ucsc.saccer3
