channels:
  - conda-forge
  - bioconda
  - r
dependencies:
#  - bioconductor-medips
  - r-ggplot2
  - r-gplots
  - bioconductor-medips
  - bioconductor-bsgenome.hsapiens.ucsc.hg19
  - bioconductor-bsgenome.hsapiens.ucsc.hg38
  - bioconductor-bsgenome.scerevisiae.ucsc.saccer3
