#########################################
## PATH for pipeline and working diretory
pipeline_dir: /cluster/home/yzeng/snakemake/tcge-cfmedip-seq-pipeline
pipeline_env: /cluster/home/yzeng/miniconda3/envs/tcge-cfmedip-seq-pipeline
workdir: /cluster/projects/tcge/cell_free_epigenomics/test_run/HNSC     ## arabidopsis only

#################################
## Sequencing samples information
## PDAC
#samples: /cluster/projects/tcge/cell_free_epigenomics/test_dataset/PDAC.tsv         ## umi-tools deup : AssertionError: not all umis are the same length(!):  7 - 8
#samples: /cluster/projects/tcge/cell_free_epigenomics/test_dataset/PDAC_1000.tsv   ## for interactive testing

## HNSC
samples: /cluster/projects/tcge/cell_free_epigenomics/test_dataset/HNSC.tsv
#samples: /cluster/projects/tcge/cell_free_epigenomics/test_dataset/HNSC_1000.tsv   ## for interactive testing

paired-end: True

## whether to aggreate samples
aggreate: True    ## True or False
## all processed samples to be aggreated
samples_aggr: /cluster/projects/tcge/cell_free_epigenomics/test_dataset/HNSC_aggr.tsv

############
## reference
ref_files: /cluster/projects/tcge/DB/tcge-cfmedip-seq-pepeline/hg38/hg38.tsv
bsgenome: BSgenome.Hsapiens.UCSC.hg38

##################################################################################################
## Spike-in, if it is Ture, the bwa index fore merged genomes is required and added to [ref_files]
## as bwa_idx_spikein
spike_in: True   #False ## if True, integrate human and spike-ins genome bwa index
spike_idx: /cluster/projects/tcge/DB/tcge-cfmedip-seq-pepeline/hg38/bwa_index_hg38_BAC_F19K16_F24B22/hg38_BAC_F19K16_F24B22.fa

## NA or Edit accordingly when spike_in == True !!!
## e.g.: for Arabidopsis thaliana BAC F19K16 (AC011717.6, chr1) and F24B22 (AL132957.1, chr 3)
spike_in_bsgenome_pkg: BSgenome.Athaliana.BAC.F19K16.F24B22_1.0.0.tar.gz
spike_in_bsgenome: BSgenome.Athaliana.BAC.F19K16.F24B22
spike_in_chr: AC011717.6 AL132957.1


######################################################
## UMI sequence, if it's Ture, barcode list is requied
add_umi: True       ## set as TRUE for the test run to deploy related conda env
#umi_list: /cluster/home/yzeng/snakemake/tcge-cfmedip-seq-pipeline/data/UMI_barcodes_OICR.txt

## umi regex : https://umi-tools.readthedocs.io/en/latest/regex.html
## quotes are needed
#umi_pattern: "'(?P<umi_1>^[ACGT]{3}[ACG])(?P<discard_1>T)|(?P<umi_1>^[ACGT]{3})(?P<discard_1>T)'"       ## PDAC; for NNNT or NNNNT, where N = [ATCG] : OICR : extract works, not dedup
#umi_pattern: "'(?P<umi_1>^[ACGT]{4})(?P<discard_1>[ATCG])'"        ## alternative for OICR UMIs, add all first 5 bases as the UMI
umi_pattern: "'(?P<umi_1>^[ACGT]{2})(?P<discard_1>T)'"        # "'(?P<umi_1>^.{2})(?P<discard_1>T)'"          ## HNSC NNT

####################
## other parameters
window_size: 300       ## methlation bin size
