workdir: /cluster/home/yzeng/tmp

## sample information
samples: /cluster/home/yzeng/snakemake/cfmedip-seq-pipeline/test/data/sample_se.tsv
paired-end: False

## reference
bwa_index: /cluster/home/yzeng/snakemake/cfmedip-seq-pipeline/test/data/Reference/genome.fa
bsgenome: BSgenome.Scerevisiae.UCSC.sacCer3
