workdir: /path/to/tcge-cfmedip-seq-pipeline-test-run
pipeline_dir: /cluster/home/yzeng/snakemake/tcge-cfmedip-seq-pipeline

## sample information
samples: /path/to/tcge-cfmedip-seq-pipeline/test/data/sample_pe.tsv
paired-end: True

## reference genome for testing datasets
bwa_index: /path/to/cfmedip-seq-pipeline/test/data/Reference/genome.fa
bsgenome: BSgenome.Scerevisiae.UCSC.sacCer3
