#workdir: /cluster/home/yzeng/tmp_1
workdir: /cluster/projects/tcge/cell_free_epigenomics/test_run/tmp

## sample information
samples: /cluster/home/yzeng/snakemake/cfmedip-seq-pipeline/test/data/sample_pe.tsv
paired-end: True

## reference
bwa_index: /cluster/home/yzeng/snakemake/cfmedip-seq-pipeline/test/data/Reference/genome.fa
bsgenome: BSgenome.Scerevisiae.UCSC.sacCer3
