samples: /Users/yong/OneDrive_UHN/Projects/snakemake/cfmedip-seq-pipeline/test/data/sample_pe.tsv

paired-end: True

bwa_index: /Users/yong/OneDrive_UHN/Projects/snakemake/cfmedip-seq-pipeline/test/data/Reference/genome.fa

workdir: /Users/yong/tmp
